#!/bin/sh
#
# Copyright (c) 2022 Omar Polo <op@omarpolo.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

me=$(basename "$0")

usage() {
	echo "usage: $me [-an] [-w wordlist] [len]" >&2
	exit 1
}

wordlist=
chars="[:print:]"
len=32

while getopts anw: ch; do
	case $ch in
	a)	chars="[:alnum:]" ;;
	n)	chars="[:digit:]" ;;
	w)	wordlist="$OPTARG"; len=6 ;;
	?)	usage ;;
	esac
done
shift $(($OPTIND - 1))

[ $# -gt 1 ] && usage
[ $# -eq 1 ] && len="$1"

if [ -n "$wordlist" ]; then
	passphrase=$(sort -R "$wordlist" | head -n "$len")
	[ -n "$passphrase" ] && echo $passphrase
else
	export LC_ALL=C
	tr -cd "$chars" </dev/urandom | dd bs=1 count="$len" 2>/dev/null && \
		echo
fi
