.\" Copyright (c) 2021, 2022, 2023 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd August 30, 2023
.Dt PWG 1
.Os
.Sh NAME
.Nm pwg
.Nd password generator
.Sh SYNOPSIS
.Nm
.Op Fl an
.Op Fl w Ar wordlist
.Op Ar length
.Sh DESCRIPTION
.Nm
generates a random string of characters or a diceware-style pass
phrase using wordlist, a file with one word per line.
The random properties are the ones provided by the operating system'
.Pa /dev/urandom
device.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
Use only alphanumeric characters.
.It Fl n
Use only numbers.
.It Fl w Ar wordlist
Generate a passphrase from a the given
.Ar wordlist
instead of a random string of characters.
.El
.Pp
If no
.Ar length
is given, an appropriate one is used.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Generate a passphrase using the EFF
.Dq large
wordlist:
.Bd -literal
$ ftp \-o\- https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt \e
	| awk '{print $2}' >~/wordlist
$ pwg \-w ~/wordlist
elm retouch disclose snaking pregame bonfire
.Ed
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Omar Polo Aq Mt op@omarpolo.com .
